spring.application.name=spring-boot-demo
spring.mail.host=smtp.gmail.com
management.endpoints.web.exposure.include=*
server.tomcat.mbeanregistry.enabled=true
management.tracing.sampling.probability=1
logging.level.org.springframework.security=DEBUG
